### ISSUE TITLE
[BUG] No option menu OTA

### ISSUE THREAD

**Issue by rdlvm** [mmakaay/esphome-yeelight_bs2#119]
Hello, installed on my bed lamp 2 working correctly, but I can't see the ota update menu on the device's website. Attached images.

![camphoto_824023566](https://github.com/mmakaay/esphome-xiaomi_bslamp2/assets/56409767/f4c4fc7f-4141-453c-966b-b0373895c6d2)

![camphoto_1691952160](https://github.com/mmakaay/esphome-xiaomi_bslamp2/assets/56409767/d447bfa9-5903-48a3-b42e-4ffcb13b17a9)

I do something wrong? thanks in advance

**Comment by mmakaay** [comment]
I'm surprised you got the web server working at all :-)
Apparently, the web server support for ESP-IDF builds is now part of the ESPHome standard code, nice! This wasn't true for quite a while after ESP-IDF support was added to ESPHome.

I assume that OTA is not (yet) implemented for the ESP-IDF-based web server. This is not an issue with the lamp firmware or with the configuration that you used. 

Looked it up in the docs, and the assumption is correct.
See: https://esphome.io/components/web_server#configuration-variables

> **ota (Optional, boolean):** Turn on or off the OTA feature inside webserver. Strongly not suggested without enabled authentication settings. Defaults to true. Cannot be used with the esp-idf framework.

Closing this issue therefore, since this is not something that I can fix.
