### ISSUE TITLE
Error: Could not find the package with 'platformio/toolchain-xtensa32 @ ~2.80400.0' requirements for your system 'linux_aarch64'

### ISSUE THREAD

**Issue by cracrama** [mmakaay/esphome-yeelight_bs2#63]
Hiya 
After update to 2021.10.0 (and later) I'm getting  error. 

Obviously old config returned plenty of errors after update of ESPhome 
So I have removed old code and copied new config from your Github and on the begining of  compiling I'm getting below: 

INFO Reading configuration /config/esphome/bedside-lamp.yaml...
INFO Updating https://github.com/mmakaay/esphome-xiaomi_bslamp2@dev
INFO Generating C++ source...
INFO Compiling app...
Processing bedside-lamp (board: esp32doit-devkit-v1; framework: espidf; platform: espressif32 @ 3.3.2)
Tool Manager: Installing platformio/toolchain-xtensa32 @ ~2.80400.0
Error: Could not find the package with 'platformio/toolchain-xtensa32 @ ~2.80400.0' requirements for your system 'linux_aarch64'

Is this something with ESPhome itself or can I correct it somehow? 

I'm using "old" config file where I have just pasted new config. 
Please advise. 
Best regards.

**Comment by mmakaay** [comment]
This happens when using an ESP-IDF build (which is what the current configuration for the Bedside Lamp 2 is using) on a Raspberry Pi.

It is not a problem with your config, but it's related to the named package not being available for the CPU type that the Raspberry Pi uses. Compiling on intel/amd Linux does work. This would happen for all projects that use the new ESP-IDF framework support for ESP32 chips, so I would indeed call it an ESPHome issue yes.

I have no work-around for this at this moment, other than compiling on a different architecture. I want to spin up ESPHome on a Raspberry Pi this weekend though, to check if I can find a solution for this.

**Comment by mmakaay** [comment]
An idea that I had for working around this, is using an older platform package for the xtensa32 tool chain. I haven't tested this out on a Raspberry yet, but this is what the syntax would look like. No promises, but you can try if this works for your setup.

Add platform_options to your esphome section. The relevant items:
```
esphome:
  platformio_options:
    platform_packages:
      - toolchain-xtensa32@2.80200
```

##Update:

I tried this on a Raspberry Pi, and while the toolchain gets installed with this, the build fails quite early, complaining that the `as` tool cannot be executed. Not a healthy build environment :-/ Back to the drawing board

![image](https://user-images.githubusercontent.com/470371/138536559-500e02ee-742e-4e86-93fc-5f60a2d99d36.png)

**Comment by cracrama** [comment]
Many thanks for clear explanation.
Really appreciate your work and great communication. 👍 
I will highlight issue on ESPhome board. 
Best regards.

**Comment by tabacha** [comment]
see: https://github.com/esphome/issues/issues/2607
