### ISSUE TITLE
Support for Yeelight LED Smart LAMP D2 - YLCT01YL

### ISSUE THREAD

**Issue by manunited10** [mmakaay/esphome-yeelight_bs2#67]
Greetings, I was hoping maybe there could be a support for Yeelight  LED Smart LAMP D2 - YLCT01YL. 
The board `looks` similar to the one here, yet simpler.
It's micro processor is `ESP-WROOM-32D` (esp32).
I attached a few photos as well.
It has two touch controls whose controller is ChipON KF8TS2716.
I haven't even turned it on. I hope somebody could guide me before I return it
![IMG_20211121_192708](https://user-images.githubusercontent.com/51100774/142755576-f6d63164-d44b-4184-9adb-9d81428b4bd4.jpg)
![IMG_20211121_192738](https://user-images.githubusercontent.com/51100774/142755581-fa69ba34-2a10-402d-802b-acb4f96e16ce.jpg)
!

**Comment by mmakaay** [comment]
That lamp is different from the Bedside Lamp 2. The touch controller is different for a start.
The PCB is white, but apart from that I cannot tell if it's indeed similar to the bslamp2.
The CPU is the same, so knowledge from this project could be useful.
When the color output channels use the same mad schema as the bslamp2, then that part could be reused. No way to tell if that is the case from these photographs.

I don't own this type of lamp myself, so I cannot do any investigations on this. I suspect that support for this lamp would best belong in a separate repository because of the differences.
If anyone reverse engineers this lamp and finds that the LEDs are driven using the same logic as the bslamp2, then let me know and we'll have to find a way to make the color handling a shared component.

I'll close this ticket now, since it's not really an issue, nor fulfillable feature request for this project.
Feel free to add more comments to this discussion though.

**Comment by mmakaay** [comment]
I purchased a D2 lamp to see if I can get a working firmware for it.
You can follow progress on the HA Community forums:
https://community.home-assistant.io/t/custom-firmware-esphome-xiaomi-bedside-lamp-d2/550880

**Comment by trmendes** [comment]
Hi @mmakaay . I'm checking the link and the last post is from 3 months ago. Are you still working on it?

I have a D2 lamp and it has the original firmware. I would like to try your firmware in a hope to fix an issue with the lamp.

Thanks for your work :)
