### ISSUE TITLE
Did I brick my bslamp2?

### ISSUE THREAD

**Issue by Sakul85** [mmakaay/esphome-yeelight_bs2#83]
Hello together and thank you all very much for this project and your effort!

After LAN-control was disabled by Xiaomi/Yeelight and broke my home automation, I tried this mod to bring it back to live.

Everything worked well (opening the lamp, soldering wires, making backup of ESP and flash firmware file compiled by esp home dashboard) but finally after everything was done the lamp could not be switched on anymore and it's not connecting to WiFi :-(

Then I restored the original .bin image but it's still not working. I am a bit confused, because the connection and flashing ESP is still working without an error message.

Can anybody help me with this? Should I provide you anthing that can help?

Thank you very much!

![1653936322232](https://user-images.githubusercontent.com/86525742/171046757-ca1f5d62-c04b-4b70-b75a-a8ba377d8f5e.jpg)

**Comment by mmakaay** [comment]
Did you disconnect the GPIO0 to GND connection after flashing?
Looking at the picture it is dicsonnected from ground, but if you had it connected, then the device would only boot into flashing mode, which would result in the symptoms that you described here.

When connecting via serial to view the device logging, do you see any logging when powering on the device?

Comforting words coming up:

In general, there is nog much risk in bricking the lamp by flashing. It is always possible to flash a bootloader and application partitions, regardless if earlier flashing attempts failed or not. I have done many broken flash operations on my lamp during development and always was able to restore by means of a direct serial connection for flashing (instead of OTA WiFi).

**Comment by Sakul85** [comment]
You have given me the decisive hint. After checking console I noticed that it's still in flashing mode. 

```
[21:25:00]rst:0x1 (POWERON_RESET),boot:0x2 (DOWNLOAD_BOOT(UART0/UART1/SDIO_REI_FEO_V2))
[21:25:00]waiting for download
```
So I removed the soldering point from GPIO and cleaned it. Then it booted correctly. It looks like the point next to GPIO is also GND. So you have to solder carefully.

Maybe you can add this to your wiki if you want.

Thank you very much! :-)

![IMG_20220613_220051](https://user-images.githubusercontent.com/86525742/173435374-01568fd4-86f9-42c6-bc06-548c6ff58908.jpg)

**Comment by mmakaay** [comment]
Ah yes, joining those ought to be avoided :-) 
I will add it to the docs, thanks!

Is it working now? Then I will close the issue after updating the docs.

**Comment by Sakul85** [comment]
Yes, its working. Please close it.

**Comment by mmakaay** [comment]
And docs have a warning now
