### ISSUE TITLE
[FEATURE] Wake up light 

### ISSUE THREAD

**Issue by TheFes** [mmakaay/esphome-yeelight_bs2#90]
**Is your feature request related to a problem? Please describe.**
It would be great if we could use the lamp as a wake-up light. However the difference between 1% brightness (night mode) and 2% is rather big, and I think the 2% brightness is already too bright to slowly wake up. Is it possible to access the light levels in between?

**Describe the solution you'd like**
Slowly (in a configurable time period) go from low brightness and warm light to high brightness cold light, where it also uses the light levels between 1% brightness and 2%.

**Describe alternatives you've considered**
Using `light.turn_on` with `transition` in HA doesn't seem to work, it immediately goes to the set brightness without a transition, so the only way I can come up with is a HA script using a repeat to slowly increase brightness, however that doesn't remove the big gap between 1% and 2%

**Comment by mmakaay** [comment]
It would be great if the brightness levels in between were available, and I tried really hard to get that working when writing the firmware. Unfortunately, this step in brightness is bound to the hardware instead of the software. I tried increasing the output levels for controlling the LEDs using really small intervals, but there always was this big jump in brightness.

So I do understand what you're after (I wanted it too), but I'll have to close this issue since I don't think it can be implemented in the firmware.
